.PHONY: clean All

All:
	@echo "----------Building project:[ Maveric_myCopter_linux - Debug ]----------"
	@cd "/media/julien/Data/Documents/Robots/maveric/Code/Maveric_myCopter" && $(MAKE) -f  "Maveric_myCopter_linux.mk" && $(MAKE) -f  "Maveric_myCopter_linux.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Maveric_myCopter_linux - Debug ]----------"
	@cd "/media/julien/Data/Documents/Robots/maveric/Code/Maveric_myCopter" && $(MAKE) -f  "Maveric_myCopter_linux.mk" clean
