.PHONY: clean All

All:
	@echo "----------Building project:[ Maveric_emu - Debug ]----------"
	@cd "/media/julien/Data/Documents/Robots/maveric/Code/Maveric_emu" && $(MAKE) -f  "Maveric_emu.mk"
clean:
	@echo "----------Cleaning project:[ Maveric_emu - Debug ]----------"
	@cd "/media/julien/Data/Documents/Robots/maveric/Code/Maveric_emu" && $(MAKE) -f  "Maveric_emu.mk" clean
