.PHONY: clean All

All:
	@echo "----------Building project:[ Maveric_emu - Debug ]----------"
	@$(MAKE) -f  "Maveric_emu.mk"
clean:
	@echo "----------Cleaning project:[ Maveric_emu - Debug ]----------"
	@$(MAKE) -f  "Maveric_emu.mk" clean
