.PHONY: clean All

All:
	@echo "----------Building project:[ Mavric_MobRob_linux - Debug ]----------"
	@$(MAKE) -f  "Mavric_MobRob_linux.mk" && $(MAKE) -f  "Mavric_MobRob_linux.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Mavric_MobRob_linux - Debug ]----------"
	@$(MAKE) -f  "Mavric_MobRob_linux.mk" clean
